services:
  - type: web
    name: asp-rental-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py makemigrations --noinput && python manage.py migrate --fake-initial --noinput && python manage.py migrate --noinput
    startCommand: gunicorn roombook.wsgi:application
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: asp-rental-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11
      - key: BASE_URL
        value: https://ai-powered-asp-room-rental-system-3.onrender.com
      - key: GOOGLE_OAUTH2_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH2_CLIENT_SECRET
        sync: false
      - key: DJANGO_SETTINGS_MODULE
        value: roombook.settings

databases:
  - name: asp-rental-db
    plan: free
